project:
  name: funcar-service
  version: 0.1
  description: A simple car buy platform

spring:
  datasource:
    url: jdbc:h2:mem:FUNCAR
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
    initialization-mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true


  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

